### ISSUE TITLE
syntax error on line 209

### ISSUE THREAD

**Issue by lofiy** [ramsessalcedo/xyz#1]
on line 209 when i reun xyz.py i get this error "ait ctx.send(embed=plan, file=file)
                                                                               ^
                                                                    SyntaxError: invalid syntax"

**Comment by ramsessalcedo** [comment]
Very simple fix. If you look at the lines above for similar code, you will see that I cut off the word "await" by accident. Pushed an update.

**Comment by lofiy** [comment]
> Very simple fix. If you look at the lines above for similar code, you will see that I cut off the word "await" by accident. Pushed an update.

Thanks i already fixed it but thanks
